apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry
spec:
  selector:
    matchLabels:
      app: telemetry
  template:
    metadata:
      labels:
        app: telemetry
    spec:
      containers:
      - name: telemetry
        image: aksdevreg.azurecr.io/telemetry:v1

        ports:
        - containerPort: 8000

