apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
spec:
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
      - name: ingestion-service
        image: aksdevreg.azurecr.io/ingestion:v1
        ports:
        - containerPort: 8000
