apiVersion: v1
kind: Service
metadata:
  name: ingestion-svc
spec:
  type: {{ .Values.axiondataInestion.service.type }}
  selector:
    app: ingestion-service
  ports:
  - port: {{ .Values.axiondataInestion.service.port }}
    targetPort: {{ .Values.axiondataInestion.service.targetPort }}